export const ADDRESS_STATUS = {
  ONLINE_ASSIGNED: '0',
  ONLINE_UNASSIGNED: '1',
  OFFLINE_ASSIGNED: '2',
  OFFLINE_UNASSIGNED: '3',
}

export const STATUS_COLOR = {
  [ADDRESS_STATUS.ONLINE_ASSIGNED]: '#00B42A',
  [ADDRESS_STATUS.ONLINE_UNASSIGNED]: '#FF7D00',
  [ADDRESS_STATUS.OFFLINE_ASSIGNED]: '#2F54EB',
  [ADDRESS_STATUS.OFFLINE_UNASSIGNED]: '#A5A9BC'
}

export const STATUS_LABEL = {
  [ADDRESS_STATUS.ONLINE_ASSIGNED]: 'cmdb.ipam.assignedOnline',
  [ADDRESS_STATUS.ONLINE_UNASSIGNED]: 'cmdb.ipam.unassignedOnline',
  [ADDRESS_STATUS.OFFLINE_ASSIGNED]: 'cmdb.ipam.assignedOffline',
  [ADDRESS_STATUS.OFFLINE_UNASSIGNED]: 'cmdb.ipam.unused'
}

export const STATUS_OPTION = [
  {
    value: ADDRESS_STATUS.ONLINE_ASSIGNED,
    label: STATUS_LABEL[ADDRESS_STATUS.ONLINE_ASSIGNED],
  },
  {
    value: ADDRESS_STATUS.ONLINE_UNASSIGNED,
    label: STATUS_LABEL[ADDRESS_STATUS.ONLINE_UNASSIGNED],
  },
  {
    value: ADDRESS_STATUS.OFFLINE_ASSIGNED,
    label: STATUS_LABEL[ADDRESS_STATUS.OFFLINE_ASSIGNED],
  },
  {
    value: ADDRESS_STATUS.OFFLINE_UNASSIGNED,
    label: STATUS_LABEL[ADDRESS_STATUS.OFFLINE_UNASSIGNED],
  }
]
